
## TABLAS DE BIBLIOTECA ##
create table LIBRO(
ID_COD_BARRA int PRIMARY KEY,
ISBNACT_LIB INT,
ISBNORIG_LIB INT,
TITULO_LIB VARCHAR(100) NOT NULL,
NUMPAG_LIB INT(4),
/*ID_MATERIA INT, FK  LO QUITO POR REQUERIMIENTOS DE DOCUMENTO*/
AÑOPUBLI_LIB YEAR,
EDICION_LIB  VARCHAR(40),
ID_EDITORIAL INT /*fk*/
/* ID_IDIOMA INT LO QUITO POR REQUERIMIENTOS EN EL DOCUMENTOS */

)ENGINE=InnoDB;

CREATE TABLE AUTORES_DE_LIBROS(
ID_LIBRO INT,
ID_AUTOR INT
)ENGINE=InnoDB;

CREATE TABLE COMPRALIBROS(
ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
NUMFACT_COMP INT,
ID_TIPODOC INT, /*FK*/
FECHAFAC_COMP DATE,
VALOR_SUBTOTAL_COMP INT,
IVA_total INT,
VALORTOT_COMP_total INT,
ID_RUT_DISTRIBUIDOR INT, /*FK*/
ID_RUT_TRAB INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE DETALLE_COMPRALIBRO(
ID_DETALLE_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
ID_COMPRA_FK INT, /*FK COMPRA*/
COD_BARRA_LIB int,
CANTIDAD_UNI INT,
VALORNETO_UNI INT,
DESCUENTO_UNI BIT,
TOTAL_UNI INT
)ENGINE=InnoDB;

CREATE TABLE COPIASLIB(
ID_COPIALIB INT PRIMARY KEY auto_increment,
ID_COD_BARRA INT, /*fk*/
NUMCOPIA_LIB INT,
OBSERVACION VARCHAR(255),
ID_COPIALIB_TIPO_VNT_FK INT, /*FK CORRESPONDE A SI ES PARA PRESTAMO O VENTA*/
ID_COMPRA INT, /*fk*/
Estado BOOLEAN
)ENGINE=InnoDB;



CREATE TABLE COPIALIB_TIPO_VENTA(
ID_COPIALIB_TIPO_VNT INT PRIMARY KEY  AUTO_INCREMENT,
DESCRIPCION VARCHAR(100) /* VENTA O PRESTAMO*/
)ENGINE=InnoDB;

CREATE TABLE USADOS_VENTA(
ID_USADOVTA INT PRIMARY KEY AUTO_INCREMENT,
ID_COD_BARRA INT,
ID_COPIALIB INT,
ID_ESTADO_LIB_USA INT, /*FK DE TABLA ESTADO LIB USADO*/
FECHA_BAJA DATE,
ID_RUTTRA INT
)ENGINE=InnoDB;

CREATE TABLE ESTADO_LIB_USADO(
ID_ESTADOLIBUSD INT PRIMARY KEY AUTO_INCREMENT,
DESCRIP_ESTLIBUS VARCHAR(100) NOT NULL,
DESCTO_ESTLIBUS BIT
)ENGINE=InnoDB;


CREATE TABLE STOCK_LIB(
ID_STOCK INT PRIMARY KEY,
ID_COD_BARRALIB INT, /*fk*/
CANT_LIB INT
)ENGINE=InnoDB;


CREATE TABLE MATERIA(
ID_MATERIAS INT PRIMARY KEY AUTO_INCREMENT,
DESCRIP_MAT VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE LIBRO_MATERIA(
ID_LIBMAT INT PRIMARY KEY AUTO_INCREMENT,
ID_COD_BARRA INT, /*fk*/
ID_SUBMAT INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE SUBMATERIA(
ID_SUBMAT INT PRIMARY KEY AUTO_INCREMENT,
DESCRIP_MAT VARCHAR(200) NOT NULL,
ID_MATERIA INT /*FK*/
)ENGINE=InnoDB;


CREATE TABLE AUTOR(
ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_AUT VARCHAR(100) NOT NULL,
PATERNO_AUT VARCHAR(100) NOT NULL,
MATERNO_AUT VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE IDIOMAS(
ID_IDIOMA INT PRIMARY KEY AUTO_INCREMENT,
IDIOMA VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE EDITORIAL(
ID_EDITORIAL INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_EDIT VARCHAR(255) NOT NULL,
DIRECCION_EDIT VARCHAR(255),
ID_PAIS INT, /*FK*/
FONO_EDIT VARCHAR(50),
URL_EDIT VARCHAR(100),
EMAIL_EDIT VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE TRABAJADORES(
ID_RUTTRA INT(8) PRIMARY KEY,
NOM_TRAB VARCHAR(100) NOT NULL,
PAT_TRAB varchar(100) NOT NULL,
MAT_TRAB VARCHAR(100),
FECNAC_TRAB YEAR,
ID_SEXO_TRAB INT, 			/*FK*/
ID_CARGO_TRAB INT,			 /*FK*/
SEXUALIDAD_TRAB INT,
ID_ECIVIL_FK INT,			 /*FK*/
ID_PAIS_TRAB_FK INT,		 /*FK*/
FECHA_CONTRATO DATE NOT NULL,
FECHA_FINCONT DATE,
ID_RUTTRA_CREA INT,			/*FK*/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, 			/*FK*/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;

CREATE TABLE SEXO(
ID_SEXO INT primary KEY auto_increment,
DESCRIPCION_SEXO VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE PRECIO_LIBROS(
ID_PREC_LIB INT PRIMARY KEY AUTO_INCREMENT,
ID_COD_BARRA INT, /*FK*/
VAL_ULT_COMP INT,
VALOR_PROM_COMP int,
VALOR_ANTECOMP INT,
PRECIO_ARRIENDO_DIARIO INT,
PRECIOVENTA INT
)ENGINE=InnoDB;

CREATE TABLE VENTA_LIBRO(
ID_VENTA INT PRIMARY KEY AUTO_INCREMENT,
ID_TIPODOC INT, /*FK*/
FECHA_VENTA DATE,
ID_RUTTRA INT, /*FK*/
ID_CLIENTE INT, /*FK*/
SUBTOTAL INT,
IVA INT,
TOTAL_VENTA INT
)ENGINE=InnoDB;

CREATE TABLE DETALLE_VENTA_LIBRO(
ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
ID_VENTA_FK INT, /*fk*/
ID_COD_BARRA_LIB INT, /*fk*/
ID_TIPO_LIB  INT, /*fk*/
ID_USADOVTA INT, /*fk*/
CANTIDAD INT,
NETO_DETVTA INT,
IVA_DETVTA INT,
VALOR_DETVTA INT
)ENGINE=InnoDB;


CREATE TABLE TIPO_LIBRO( /* SI ES USADO O NUEVO*/
ID_TIPO_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION_TIPO_LIBRO VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE DETALLE_PAGO(
ID_DETPAGO INT PRIMARY KEY AUTO_INCREMENT,
ID_FORMA_PAGO INT, /*FK*/
MONTO INT,
ID_VENTA INT /*FK*/
)ENGINE=InnoDB;



CREATE TABLE PROVEEDOR(
ID_RUTPROV INT(8) PRIMARY KEY,
NOM_PRO VARCHAR(100) not null ,
PAT_PROV VARCHAR(100),  
MAT_PROV VARCHAR(100),
TIPO_PROV INT, /* NOSE QUE MIERDA HACE ACA ESOT*/
WEBSITE VARCHAR(255),
RAZONSOCIAL_PROV VARCHAR(255) NOT NULL,
ID_ACTECO_FK INT, /*ACTIVIDAD ECONOMICA*/
NOM_RLEGAL_CLI VARCHAR(100),
PAT_RLEGAL_CLI VARCHAR(100),
MAT_RLEGAL_CLI VARCHAR(100),
ID_RUTTRA_CREA INT, /*FK*/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /*FK*/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;

CREATE TABLE TIPO_DOCUMENTO(
ID_TIPODOC INT PRIMARY KEY,
DESCRICPION_TIPODOC VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE FORMA_PAGO(
ID_FORMA_PAGO INT PRIMARY KEY auto_increment,
DESCRIPCION VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE CARGOS(
ID_CARGOTRAB INT PRIMARY KEY auto_increment,
DESCRIPCION_CG VARCHAR(100)
)ENGINE=InnoDB;

CREATE TABLE CARGO_TRABAJADOR(
ID_TRABCARG INT PRIMARY KEY AUTO_INCREMENT,
ID_RUTTRA INT, /**/
ID_CARGO INT, /**/
FECHA_INIC DATE,
FECHA_FIN DATE,
MOTIVO_FIN_CONTRATO VARCHAR(100),
ESTADO BOOLEAN
)ENGINE=InnoDB;


CREATE TABLE PRESTAMO_LIBROS(
ID_PRESTAMO INT primary KEY AUTO_INCREMENT,
FECHA_PRESTAMO DATE,
ID_RUTCLI INT, /**/
ID_RUTTRA INT, /**/
SUBTOTAL_PRESTAMO INT,
IVA INT,
TOTAL_PRESTAMO INT
)ENGINE=InnoDB;

CREATE TABLE PRESTAMO_LIBRO_DETALLE(
ID_DETALLE_PRESTAMO INT PRIMARY KEY AUTO_INCREMENT,
ID_PRESTAMO INT, /**/
ID_COD_BARRA INT, /**/
ID_COPIALIB INT, /**/
VALOR_PRESTAMO_LIBRO INT
)ENGINE=InnoDB;


CREATE TABLE PRESTAMO_DEVOLUCION(
ID_PRESTAMO_DEVOLUCION INT PRIMARY KEY AUTO_INCREMENT,
ID_RUTCLI INT, /*FK*/
ID_PRESTAMO INT, /*fk*/
FECHA_PRESTAMO date,
FECHA_ENTREGA_REAL DATE,
DIAS_RETRESO INT,
VALOR_PRESTAMO INT,
MULTA INT,
COSTO_FINAL_PRESTAMO INT
)ENGINE=InnoDB;

CREATE TABLE STOCK_LIB_PRESTAMO( 
/* NO LE ENCUENTRO SENTIDO YA QUE CON UN COUNT() SE PUEDE SABER EL STOCK CON LA TABLA COPIALIB*/
ID_STOCK_PRESTAMO INT PRIMARY KEY AUTO_INCREMENT,
ID_COD_BARRALIB INT, /**/
CANT_LIB INT
)ENGINE=InnoDB;

CREATE TABLE CLIENTES(
ID_RUTCLI INT(8) PRIMARY KEY,
NOM_CLI VARCHAR(100) NOT NULL,
PATERNO_CLI VARCHAR(100) NOT NULL,
MATERNO_CLI VARCHAR(100),
ID_TIPO_CLI INT, /*FK*/
ID_ESTADO_CIVIL INT, /*FK*/
RAZONSOCIAL_CLI VARCHAR(255),
ID_ACTIV_ECONO INT, /*FK*/
NOM_RLEGAL_CLI VARCHAR(100),
PAT_RLEGAL_CLI VARCHAR(100),
MAT_RLEGAL_CLI VARCHAR(100),
ID_RUTTRA_CREA INT,
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT,
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;


CREATE TABLE ACTIVIDAD_ECONOMICA(
ID_ACTECO INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION_ACT VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE CORREOS(
ID_CORREO INT PRIMARY KEY AUTO_INCREMENT,
DIR_EMAIL VARCHAR(255) NOT NULL,
ID_RUTTRA_CREA INT, /**/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /**/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;

#TABLAS INTERMEDIAS DE CORREOS
CREATE TABLE CORREOS_DE_CLIENTES(
ID_RUTCLI INT,
ID_CORREO INT
)ENGINE=InnoDB;

CREATE TABLE CORREOS_DE_TRABAJADORES(
ID_RUTTRA INT,
ID_CORREO INT
)ENGINE=InnoDB;

CREATE TABLE TIPO_CLIENTE(
ID_TIPOCLI INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION_TIPOCLI VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE TELEFONO( /*FALTA TABLA INTERMEDIA PARA ASIGNAR MANY TO MANY*/
ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
TELEFONO VARCHAR(100) NOT NULL,
ID_RUTTRA_CREA INT, /**/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /**/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;

#TABLAS INTERMEDIAS DE TELEFONOS
CREATE TABLE TELEFONOS_DE_CLIENTES(
ID_RUTCLI INT,
ID_TELEFONO INT
)ENGINE=InnoDB;



CREATE TABLE TELEFONOS_DE_TRABAJADORES(
ID_RUTTRA INT,
ID_TELEFONO INT
)ENGINE=InnoDB;


CREATE TABLE DIRECCION(
ID_DIRECCION INT PRIMARY KEY AUTO_INCREMENT,
ID_TIPODIR_FK INT, /**/
CALLE VARCHAR(255) NOT NULL,
NUMERO INT(6),
ID_COMUNA_FK INT, /**/
POBLACION VARCHAR(100),
BLOCKS VARCHAR(6),
DEPARTAMENTO VARCHAR(6),
SECTOR VARCHAR(50),
CODIGO_POSTAL CHAR(7),
ID_RUTTRA_CREA INT, /**/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /**/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;


#TABLAS INTERMEDIAS DE DIRECCIONES
CREATE TABLE DIRECCIONES_DE_CLIENTES(
ID_RUTCLI INT,
ID_DIRECCION INT
)ENGINE=InnoDB;


CREATE TABLE DIRECCIONES_DE_TRABAJADORES(
ID_RUTTRA INT,
ID_DIRECCION INT
)ENGINE=InnoDB;


CREATE TABLE TIPO_DIRECCION(
ID_TIPODIR INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE CONTACTO(
ID_CONTACTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CTC VARCHAR(100) NOT NULL,
PAT_CTC VARCHAR(100) NOT NULL,
MAT_CTC VARCHAR(100),
ID_RUTCLI_FK INT, /**/
ID_RUTTRA_CREA INT, /**/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /**/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;


CREATE TABLE PAIS(
ID_PAIS INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PAIS VARCHAR(100) NOT NULL,
NACIONALIDAD_PAIS VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE ESTADO_CIVIL(
ID_ECIVIL INT PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION_ECIVIL CHAR(20)
)ENGINE=InnoDB;

CREATE TABLE COMUNA(
ID_COMUNA INT PRIMARY KEY,
NOMBRE_COMU VARCHAR(150) NOT NULL,
ID_PROVINCIA_FK INT /**/
)ENGINE=InnoDB;

CREATE TABLE PROVINCIA(
ID_PROVINCIA INT PRIMARY KEY,
NOMBRE_PROV VARCHAR(100) NOT NULL,
ID_REGION_FK int /*fk*/
)ENGINE=InnoDB;


CREATE TABLE REGION(
ID_REGION INT primary key,
NOMBRE_REG VARCHAR(100) NOT NULL,
NUMERO_REG VARCHAR(40) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE ANOTACIONES(
ID_ANOTACIONES INT PRIMARY KEY AUTO_INCREMENT,
FECHA_ANOTA DATETIME,
OBSERVACION VARCHAR(255),
ID_RUTTRA_CREA INT, /**/
FECHA_CREACION DATETIME,
ID_RUTTRA_MOD INT, /**/
FECHA_MODIFICA DATETIME,
Estado BOOLEAN
)ENGINE=InnoDB;
/* Un libro puede tener una o más categorías, puede tener uno o más idiomas */
CREATE TABLE CATEGORIAS_DE_LIBROS(
ID_MATERIAS INT,
ID_CODBARRA_LIB INT
)ENGINE=InnoDB;

CREATE TABLE IDIOMAS_DE_LIBROS(
ID_IDIOMA INT,
ID_CODBARRA_LIB INT
)ENGINE=InnoDB;




