######## FOREIGN KEYS ########################

ALTER TABLE CATEGORIAS_DE_LIBROS
ADD constraint FK_CATEGORIAS_DE_LIBROS_ID_MATERIAS
FOREIGN KEY (ID_MATERIAS) REFERENCES MATERIA(ID_MATERIAS);

ALTER TABLE CATEGORIAS_DE_LIBROS
ADD constraint FK_CATEGORIAS_DE_LIBROS_ID_CODBARRA_LIB
FOREIGN KEY (ID_CODBARRA_LIB) REFERENCES LIBRO(ID_COD_BARRA);

ALTER TABLE IDIOMAS_DE_LIBROS
ADD constraint FK_IDIOMAS_DE_LIBROS_ID_CODBARRA_LIB
FOREIGN KEY (ID_CODBARRA_LIB) REFERENCES LIBRO(ID_COD_BARRA);

ALTER TABLE IDIOMAS_DE_LIBROS
ADD constraint FK_IDIOMAS_DE_LIBROS_ID_IDIOMA
FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMAS(ID_IDIOMA);

ALTER TABLE ANOTACIONES
ADD constraint FK_ANOTACIONES_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE ANOTACIONES
ADD constraint FK_ANOTACIONES_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE COMUNA
ADD constraint FK_COMUNA_ID_PROVINCIA_FK
FOREIGN KEY (ID_PROVINCIA_FK) REFERENCES  PROVINCIA(ID_PROVINCIA);

ALTER TABLE PROVINCIA
ADD constraint FK_PROVINCIA_ID_REGION
FOREIGN KEY (ID_REGION_FK) REFERENCES  REGION(ID_REGION);

ALTER TABLE CONTACTO
ADD constraint FK_CONTACTO_ID_RUTCLI_FK
FOREIGN KEY (ID_RUTCLI_FK) REFERENCES  CLIENTES(ID_RUTCLI);

ALTER TABLE CONTACTO
ADD constraint FK_CONTACTO_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE CONTACTO
ADD constraint FK_CONTACTO_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);


ALTER TABLE DIRECCIONES_DE_TRABAJADORES
ADD constraint FK_DIRECCIONES_DE_TRABAJADORES_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE DIRECCIONES_DE_TRABAJADORES
ADD constraint FK_DIRECCIONES_DE_TRABAJADORES_ID_TELEFONO
FOREIGN KEY (ID_DIRECCION) REFERENCES  DIRECCION(ID_DIRECCION);


ALTER TABLE DIRECCIONES_DE_CLIENTES
ADD constraint FK_DIRECCIONES_DE_CLIENTES_ID_RUTCLI
FOREIGN KEY (ID_RUTCLI) REFERENCES  CLIENTES(ID_RUTCLI);
--
ALTER TABLE DIRECCIONES_DE_CLIENTES
ADD constraint FK_DIRECCIONES_DE_CLIENTES_ID_DIRECCION
FOREIGN KEY (ID_DIRECCION) REFERENCES  DIRECCION(ID_DIRECCION);

ALTER TABLE DIRECCION
ADD constraint FK_DIRECCION_ID_TIPODIR
FOREIGN KEY (ID_TIPODIR_FK) REFERENCES  TIPO_DIRECCION(ID_TIPODIR);

ALTER TABLE DIRECCION
ADD constraint FK_DIRECCION_ID_COMUNA
FOREIGN KEY (ID_COMUNA_FK) REFERENCES  COMUNA(ID_COMUNA);

ALTER TABLE DIRECCION
ADD constraint FK_DIRECCION_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE DIRECCION
ADD constraint FK_DIRECCION_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);


ALTER TABLE TELEFONOS_DE_CLIENTES
ADD constraint FK_TELEFONOS_DE_CLIENTES_ID_RUTCLI
FOREIGN KEY (ID_RUTCLI) REFERENCES  CLIENTES(ID_RUTCLI);
--
ALTER TABLE TELEFONOS_DE_CLIENTES
ADD constraint FK_TELEFONOS_DE_CLIENTES_ID_TELEFONO
FOREIGN KEY (ID_TELEFONO) REFERENCES  TELEFONO(ID_TELEFONO);

ALTER TABLE TELEFONOS_DE_TRABAJADORES
ADD constraint FK_TELEFONOS_DE_TRABAJADORES_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE TELEFONOS_DE_TRABAJADORES
ADD constraint FK_TELEFONOS_DE_TRABAJADORES_ID_TELEFONO
FOREIGN KEY (ID_TELEFONO) REFERENCES  TELEFONO(ID_TELEFONO);


ALTER TABLE CORREOS_DE_TRABAJADORES
ADD constraint FK_CORREOS_DE_TRABAJADORES_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE CORREOS_DE_TRABAJADORES
ADD constraint FK_CORREOS_DE_TRABAJADORES_ID_CORREO
FOREIGN KEY (ID_CORREO) REFERENCES  CORREOS(ID_CORREO);


ALTER TABLE CORREOS_DE_CLIENTES
ADD constraint FK_CORREOS_DE_CLIENTES_ID_RUTCLI
FOREIGN KEY (ID_RUTCLI) REFERENCES  CLIENTES(ID_RUTCLI);
--
ALTER TABLE CORREOS_DE_CLIENTES
ADD constraint FK_CORREOS_DE_CLIENTES_ID_CORREO
FOREIGN KEY (ID_CORREO) REFERENCES  CORREOS(ID_CORREO);

ALTER TABLE CORREOS
ADD constraint FK_CORREOS_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE CORREOS
ADD constraint FK_CORREOS_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE CLIENTES
ADD constraint FK_CLIENTES_ID_TIPO_CLI
FOREIGN KEY (ID_TIPO_CLI) REFERENCES  TIPO_CLIENTE(ID_TIPOCLI);

ALTER TABLE CLIENTES
ADD constraint FK_CLIENTES_ID_ESTADO_CIVIL
FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES  ESTADO_CIVIL(ID_ECIVIL);

ALTER TABLE CLIENTES
ADD constraint FK_CLIENTES_ID_ACTIV_ECONO
FOREIGN KEY (ID_ACTIV_ECONO) REFERENCES  ACTIVIDAD_ECONOMICA(ID_ACTECO);

ALTER TABLE CLIENTES
ADD constraint FK_CLIENTES_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE CLIENTES
ADD constraint FK_CLIENTES_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE PRESTAMO_DEVOLUCION
ADD constraint FK_PRESTAMO_DEVOLUCION_ID_RUTCLI
FOREIGN KEY (ID_RUTCLI) REFERENCES  CLIENTES(ID_RUTCLI);

ALTER TABLE PRESTAMO_DEVOLUCION
ADD constraint FK_PRESTAMO_DEVOLUCION_ID_PRESTAMO
FOREIGN KEY (ID_PRESTAMO) REFERENCES  PRESTAMO_LIBROS(ID_PRESTAMO);


ALTER TABLE PRESTAMO_LIBRO_DETALLE
ADD constraint FK_PRESTAMO_LIBRO_DETALLE_ID_PRESTAMO
FOREIGN KEY (ID_PRESTAMO) REFERENCES  PRESTAMO_LIBROS(ID_PRESTAMO);

ALTER TABLE PRESTAMO_LIBRO_DETALLE
ADD constraint FK_PRESTAMO_LIBRO_DETALLE_ID_COD_BARRA
FOREIGN KEY (ID_COD_BARRA) REFERENCES  libro(ID_COD_BARRA);

ALTER TABLE PRESTAMO_LIBRO_DETALLE
ADD constraint FK_PRESTAMO_LIBRO_DETALLE_ID_COPIALIB
FOREIGN KEY (ID_COPIALIB) REFERENCES  COPIASLIB(ID_COPIALIB);


ALTER TABLE PRESTAMO_LIBROS
ADD constraint FK_PRESTAMO_LIBROS_ID_RUTCLI
FOREIGN KEY (ID_RUTCLI) REFERENCES  CLIENTES(ID_RUTCLI);

ALTER TABLE PRESTAMO_LIBROS
ADD constraint FK_PRESTAMO_LIBROS_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES  TRABAJADORES(ID_RUTTRA);


ALTER TABLE CARGO_TRABAJADOR
ADD constraint FK_CARGO_TRABAJADOR_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE CARGO_TRABAJADOR
ADD constraint FK_CARGO_TRABAJADOR_ID_CARGO
FOREIGN KEY (ID_CARGO) REFERENCES  CARGOS(ID_CARGOTRAB);

#FOREIGN KEYS DE PROVEEDORES
ALTER TABLE  PROVEEDOR
ADD constraint FK_PROVEEDOR_ID_ACTECO_FK
FOREIGN KEY (ID_ACTECO_FK) REFERENCES ACTIVIDAD_ECONOMICA(ID_ACTECO);

ALTER TABLE PROVEEDOR
ADD constraint FK_PROVEEDOR_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE PROVEEDOR
ADD constraint FK_PROVEEDOR_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);


ALTER TABLE  DETALLE_PAGO
ADD constraint FK_DETALLE_PAGO_ID_FORMA_PAGO
FOREIGN KEY (ID_FORMA_PAGO) REFERENCES FORMA_PAGO(ID_FORMA_PAGO);

ALTER TABLE  DETALLE_PAGO
ADD constraint FK_DETALLE_PAGO_ID_VENTA
FOREIGN KEY (ID_VENTA) REFERENCES VENTA_LIBRO(ID_VENTA);

#FOREIGN KEYS DETALLE VENTA LIBRO
ALTER TABLE  DETALLE_VENTA_LIBRO
ADD constraint FK_DETALLE_VENTA_LIBRO_ID_VENTA_FK
FOREIGN KEY (ID_VENTA_FK) REFERENCES VENTA_LIBRO(ID_VENTA);

ALTER TABLE  DETALLE_VENTA_LIBRO
ADD constraint FK_DETALLE_VENTA_LIBRO_ID_COD_BARRA_LIB
FOREIGN KEY (ID_COD_BARRA_LIB) REFERENCES libro(ID_COD_BARRA);

ALTER TABLE  DETALLE_VENTA_LIBRO
ADD constraint FK_DETALLE_VENTA_LIBRO_ID_TIPO_LIB
FOREIGN KEY (ID_TIPO_LIB) REFERENCES TIPO_LIBRO(ID_TIPO_LIBRO);

ALTER TABLE  VENTA_LIBRO
ADD constraint FK_VENTA_LIBRO_ID_TIPODOC
FOREIGN KEY (ID_TIPODOC) REFERENCES TIPO_DOCUMENTO(ID_TIPODOC);

ALTER TABLE  VENTA_LIBRO
ADD constraint FK_VENTA_LIBRO_ID_RUTTRA
FOREIGN KEY (ID_RUTTRA) REFERENCES TRABAJADORES(ID_RUTTRA);

ALTER TABLE  VENTA_LIBRO
ADD constraint FK_VENTA_LIBRO_ID_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_RUTCLI);

ALTER TABLE  PRECIO_LIBROS
ADD constraint FK_PRECIO_LIBROS_ID_COD_BARRA
FOREIGN KEY (ID_COD_BARRA) REFERENCES libro(ID_COD_BARRA);


#fOREING KEYS TRABAJADORES
ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_SEXO_TRAB
FOREIGN KEY (ID_SEXO_TRAB) REFERENCES  SEXO(ID_SEXO);

ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_CARGO_TRAB
FOREIGN KEY (ID_CARGO_TRAB) REFERENCES  CARGO_TRABAJADOR(ID_TRABCARG);

ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_ECIVIL_FK
FOREIGN KEY (ID_ECIVIL_FK) REFERENCES  ESTADO_CIVIL(ID_ECIVIL);

ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_PAIS_TRAB_FK
FOREIGN KEY (ID_PAIS_TRAB_FK) REFERENCES  PAIS(ID_PAIS);

ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_RUTTRA_CREA
FOREIGN KEY (ID_RUTTRA_CREA) REFERENCES  TRABAJADORES(ID_RUTTRA);
--
ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_RUTTRA_MOD
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);

### NUEVO FOREIGN KEY 30/07/2020
ALTER TABLE TRABAJADORES
ADD constraint FK_TRABAJADORES_ID_SEX
FOREIGN KEY (ID_RUTTRA_MOD) REFERENCES  TRABAJADORES(ID_RUTTRA);

ALTER TABLE EDITORIAL
ADD constraint FK_EDITORIAL_ID_PAIS
FOREIGN KEY (ID_PAIS) REFERENCES  PAIS(ID_PAIS);

ALTER TABLE SUBMATERIA
ADD constraint FK_SUBMATERIA_ID_MATERIA
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIAS);

ALTER TABLE LIBRO_MATERIA
ADD constraint FK_LIBRO_MATERIA_ID_COD_BARRA
FOREIGN KEY (ID_COD_BARRA) REFERENCES LIBRO(ID_COD_BARRA);

ALTER TABLE LIBRO_MATERIA
ADD constraint FK_LIBRO_MATERIA_ID_SUBMAT
FOREIGN KEY (ID_SUBMAT) REFERENCES SUBMATERIA(ID_SUBMAT);


ALTER TABLE USADOS_VENTA
ADD constraint FK_USADOS_VENTA_ID_ESTADO_LIB_USA
FOREIGN KEY (ID_ESTADO_LIB_USA) REFERENCES ESTADO_LIB_USADO(ID_ESTADOLIBUSD);

### FALTABA ESTE FOREIGN KEY 30-07-2020
ALTER TABLE COPIASLIB
ADD CONSTRAINT FK_COPIASLIB_ID_CODBARRA
FOREIGN KEY (ID_COD_BARRA) REFERENCES LIBRO(ID_COD_BARRA);

ALTER TABLE COPIASLIB
ADD constraint FK_COPIASLIB_ID_COPIALIB_TIPO_VNT
FOREIGN KEY (ID_COPIALIB_TIPO_VNT_FK) REFERENCES COPIALIB_TIPO_VENTA(ID_COPIALIB_TIPO_VNT);

ALTER TABLE COPIASLIB
ADD constraint FK_COPIASLIB_ID_COMPRA
FOREIGN KEY (ID_COMPRA) REFERENCES COMPRALIBROS(ID_COMPRA);

ALTER TABLE STOCK_LIB
ADD constraint FK_STOCK_LIB_ESTADO_LIB_USA
FOREIGN KEY (ID_COD_BARRALIB) REFERENCES LIBRO(ID_COD_BARRA);

ALTER TABLE DETALLE_COMPRALIBRO
ADD constraint FK_DETALLE_COMPRALIBRO_ID_COMPRA_FK
FOREIGN KEY (ID_COMPRA_FK) REFERENCES COMPRALIBROS(ID_COMPRA);


ALTER TABLE COMPRALIBROS
ADD constraint FK_COMPRALIBROS_IDTIPODOC
FOREIGN KEY (ID_TIPODOC) REFERENCES TIPO_DOCUMENTO(ID_TIPODOC);

ALTER TABLE COMPRALIBROS
ADD constraint FK_COMPRALIBROS_RUTDISTR
FOREIGN KEY (ID_RUT_DISTRIBUIDOR) REFERENCES PROVEEDOR(ID_RUTPROV);

ALTER TABLE AUTORES_DE_LIBROS
ADD constraint FK_AUTORES_LIBRO_IDAUTOR
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR);

ALTER TABLE AUTORES_DE_LIBROS
ADD constraint FK_AUTORES_LIBRO_IDLIBRO
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID_COD_BARRA);

/*ALTER TABLE LIBRO
ADD constraint FK_LIBRO_MATERIA
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA);
qUITADO POR REQUERIMIENTOS DE DOCUMENTO */

ALTER TABLE LIBRO
ADD constraint FK_LIBRO_EDITORIAL
FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL(ID_EDITORIAL);